# Generated by Django 2.1.1 on 2020-01-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
