# Generated by Django 2.1.1 on 2020-01-09 00:23

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0004_connectionlink_submit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('title', models.CharField(max_length=200)),
                ('profile', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='interest',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
