# Generated by Django 2.1.1 on 2020-01-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0005_auto_20200108_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='profile',
            field=models.ImageField(blank=True, upload_to='leaders/profile_pics'),
        ),
    ]
