# Generated by Django 2.1.1 on 2020-01-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0006_auto_20200108_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='profile',
            field=models.URLField(blank=True),
        ),
    ]
