# Generated by Django 2.1.1 on 2020-01-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0007_auto_20200108_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
