# Generated by Django 2.1.1 on 2020-01-09 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0008_auto_20200108_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 19, 16, 58, 430212, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
