# Generated by Django 2.1.1 on 2020-01-09 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0009_auto_20200109_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 20, 55, 59, 503528, tzinfo=utc), null=True),
        ),
    ]
