# Generated by Django 2.1.1 on 2020-01-09 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0010_auto_20200109_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibletalk',
            name='info',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 20, 58, 42, 4614, tzinfo=utc), null=True),
        ),
    ]
