# Generated by Django 2.1.1 on 2020-01-09 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0012_auto_20200109_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibletalk',
            name='logo',
            field=models.URLField(default=datetime.datetime(2020, 1, 9, 21, 48, 51, 598274, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 21, 48, 35, 313056, tzinfo=utc), null=True),
        ),
    ]
