# Generated by Django 2.1.1 on 2020-01-09 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0014_auto_20200109_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibletalk',
            name='shorthand',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 23, 1, 22, 32806, tzinfo=utc), null=True),
        ),
    ]
