# Generated by Django 2.1.1 on 2020-01-09 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0015_auto_20200109_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 23, 1, 46, 882323, tzinfo=utc), null=True),
        ),
    ]
