# Generated by Django 2.1.1 on 2020-01-10 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0016_auto_20200109_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 10, 8, 58, 25, 228040, tzinfo=utc), null=True),
        ),
    ]
