# Generated by Django 2.1.1 on 2020-01-27 02:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0019_auto_20200126_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default='description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 27, 2, 40, 33, 15384, tzinfo=utc), null=True),
        ),
    ]
