# Generated by Django 2.1.1 on 2020-02-04 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0022_auto_20200126_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 4, 6, 3, 36, 419812, tzinfo=utc), null=True),
        ),
    ]
