# Generated by Django 2.1.1 on 2020-03-17 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0024_auto_20200226_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 17, 21, 52, 47, 150774, tzinfo=utc), null=True),
        ),
    ]
