# Generated by Django 2.1.1 on 2020-03-17 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0025_auto_20200317_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialevent',
            name='hidden',
        ),
        migrations.AddField(
            model_name='specialevent',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 17, 21, 59, 37, 761422, tzinfo=utc), null=True),
        ),
    ]
