# Generated by Django 3.1.2 on 2020-10-30 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0039_auto_20200317_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionlink',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 30, 1, 57, 27, 127788, tzinfo=utc), null=True),
        ),
    ]
